class WeatherCodes {
  static Map<int, String> codes = {
    0: "Clear sky",
    1: "Mainly clear",
    2: "Partly cloudy",
    3: "Overcast",
    45: "Fog",
    48: "Depositing rime fog",
    51: "Drizzle: Light",
    53: "Drizzle: Moderate",
    55: "Drizzle: Dense",
    56: "Freezing Drizzle: \nLight",
    57: "Freezing Drizzle: \nDense",
    61: "Rain: Slight",
    63: "Rain: Moderate",
    65: "Rain: Heavy",
    66: "Freezing Rain: \nLight",
    67: "Freezing Rain: \nHeavy",
    71: "Snow fall: \nSlight",
    73: "Snow fall: \nModerate",
    75: "Snow fall: \nHeavy",
    77: "Snow grains",
    80: "Rain showers: \nSlight",
    81: "Rain showers: \nModerate",
    82: "Rain showers: \nViolent",
    85: "Snow showers: \nSlight",
    86: "Snow showers: \nModerate",
    95: "Thunderstorm: \nSlight or moderate",
    96: "Thunderstorm with slight hail",
    99: "Thunderstorm with heavy hail",
  };
}
